# Generated by Django 3.2.8 on 2021-10-19 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='ФИО кандидата')),
                ('party', models.CharField(max_length=200, verbose_name='Партия')),
                ('info', models.TextField(verbose_name='Инфо о кандидате')),
                ('sum_votes', models.IntegerField(verbose_name='Общее число голосов')),
                ('photo', models.ImageField(upload_to='media/', verbose_name='Фото')),
            ],
        ),
        migrations.CreateModel(
            name='Protocol1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_protocol_1', models.IntegerField(verbose_name='Номер протокола 1го типа')),
                ('num_uik', models.IntegerField(verbose_name='Номер участка')),
                ('status', models.BooleanField(verbose_name='Статус')),
                ('sum_bul', models.IntegerField(verbose_name='Число полученных бюллетеней')),
                ('sum_final_bul', models.IntegerField(verbose_name='Число обработаных бюллетеней')),
                ('bad_form', models.IntegerField(verbose_name='Общее число испорченных бланков')),
                ('transfer_time', models.TimeField(auto_now=True, verbose_name='Время передачи протокола')),
            ],
        ),
        migrations.CreateModel(
            name='Uik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_uik', models.IntegerField(unique=True, verbose_name='Номер участка')),
                ('num_tik', models.IntegerField(verbose_name='Номер ТИК')),
                ('population', models.IntegerField(verbose_name='Численность')),
                ('status', models.BooleanField(verbose_name='Статус')),
                ('sum_votes', models.IntegerField(verbose_name='Общее число голосов')),
                ('sum_numb_votes_fin', models.IntegerField(verbose_name='Общее число голосов обработанное')),
                ('presence', models.IntegerField(verbose_name='Явка')),
                ('perc_final_bul', models.IntegerField(verbose_name='Процент обработанных бюллетеней')),
                ('bad_form', models.IntegerField(verbose_name='Общее число испорченных бланков')),
                ('update_time', models.TimeField(auto_now=True, verbose_name='Время последнего изменени')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя пользователя')),
                ('password', models.CharField(max_length=200, verbose_name='Пароль')),
                ('num_uik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.uik')),
            ],
        ),
        migrations.CreateModel(
            name='UikProtocol1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_protocol1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.protocol1')),
                ('id_uik', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.uik')),
            ],
        ),
        migrations.CreateModel(
            name='UikCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.candidate')),
                ('id_uik', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.uik')),
            ],
        ),
        migrations.CreateModel(
            name='Protocol2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_protocol_2', models.IntegerField(verbose_name='Номер протокола 2го типа')),
                ('num_uik', models.IntegerField(verbose_name='Номер участка')),
                ('candidate_votes', models.IntegerField(verbose_name='Число голосов за кандидата')),
                ('transfer_time', models.TimeField(auto_now=True, verbose_name='Время передачи протокола')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.candidate')),
            ],
        ),
    ]
