# Generated by Django 3.2.8 on 2021-10-25 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_delete_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocol1',
            name='bad_form',
            field=models.IntegerField(default=0, verbose_name='Общее число испорченных бланков'),
        ),
        migrations.AlterField(
            model_name='protocol1',
            name='num_protocol_1',
            field=models.IntegerField(default=0, verbose_name='Номер протокола 1го типа'),
        ),
        migrations.AlterField(
            model_name='protocol1',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='protocol1',
            name='sum_bul',
            field=models.IntegerField(default=0, verbose_name='Число полученных бюллетеней'),
        ),
        migrations.AlterField(
            model_name='protocol1',
            name='sum_final_bul',
            field=models.IntegerField(default=0, verbose_name='Число обработаных бюллетеней'),
        ),
        migrations.AlterField(
            model_name='protocol2',
            name='num_protocol_2',
            field=models.IntegerField(default=0, verbose_name='Номер протокола 2го типа'),
        ),
        migrations.AlterField(
            model_name='uik',
            name='num_tik',
            field=models.CharField(max_length=200, verbose_name='Номер ТИК'),
        ),
    ]
