# Generated by Django 3.2.8 on 2021-11-05 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20211103_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uik',
            name='num_tik',
            field=models.ForeignKey(db_column='num_tik', on_delete=django.db.models.deletion.CASCADE, to='mainapp.tik'),
        ),
    ]
