# Generated by Django 3.2.8 on 2021-10-19 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_delete_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uik',
            name='num_tik',
            field=models.CharField(max_length=200, verbose_name='Номер ТИК'),
        ),
    ]
