# Generated by Django 3.2.8 on 2021-10-26 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_uik_num_tik'),
        ('mainapp', '0003_auto_20211025_1307'),
    ]

    operations = [
    ]
