# Generated by Django 3.2.8 on 2021-11-08 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20211108_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='tik',
            name='num_tik',
            field=models.CharField(default='0', max_length=200, verbose_name='Номер ТИК'),
        ),
        migrations.AddField(
            model_name='uik',
            name='num_tik',
            field=models.CharField(default='0', max_length=200, verbose_name='Номер ТИК'),
        ),
    ]
