# Generated by Django 3.2.8 on 2021-11-05 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_uik_num_tik'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uik',
            name='num_tik',
        ),
        migrations.RemoveField(
            model_name='uik',
            name='num_uik',
        ),
        migrations.AddField(
            model_name='uik',
            name='num_uik',
            field=models.ManyToManyField(to='mainapp.Tik'),
        ),
    ]
