# Generated by Django 3.2.8 on 2021-10-26 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20211025_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uikcandidate',
            name='id_candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.candidate'),
        ),
        migrations.AlterField(
            model_name='uikprotocol1',
            name='id_protocol1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.protocol1'),
        ),
    ]
