# Generated by Django 3.2.8 on 2021-10-26 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20211026_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uikcandidate',
            name='id_uik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.uik'),
        ),
        migrations.AlterField(
            model_name='uikprotocol1',
            name='id_uik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.uik'),
        ),
    ]
