# Generated by Django 3.2.8 on 2021-11-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20211105_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='uik',
            name='num_tik',
            field=models.ManyToManyField(default='0', to='mainapp.Tik'),
        ),
        migrations.AlterField(
            model_name='tik',
            name='num_tik',
            field=models.CharField(default='0', max_length=200, verbose_name='Номер ТИК'),
        ),
        migrations.RemoveField(
            model_name='uik',
            name='num_uik',
        ),
        migrations.AddField(
            model_name='uik',
            name='num_uik',
            field=models.IntegerField(default=0, unique=True, verbose_name='Номер участка'),
        ),
    ]
