# Generated by Django 3.2.8 on 2021-10-27 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20211026_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='sum_votes',
            field=models.IntegerField(default=0, verbose_name='Общее число голосов'),
        ),
        migrations.AlterField(
            model_name='uik',
            name='bad_form',
            field=models.IntegerField(default=0, verbose_name='Общее число испорченных бланков'),
        ),
        migrations.AlterField(
            model_name='uik',
            name='perc_final_bul',
            field=models.IntegerField(default=0, verbose_name='Процент обработанных бюллетеней'),
        ),
        migrations.AlterField(
            model_name='uik',
            name='presence',
            field=models.IntegerField(default=0, verbose_name='Явка'),
        ),
        migrations.AlterField(
            model_name='uik',
            name='sum_numb_votes_fin',
            field=models.IntegerField(default=0, verbose_name='Общее число голосов обработанное'),
        ),
        migrations.AlterField(
            model_name='uik',
            name='sum_votes',
            field=models.IntegerField(default=0, verbose_name='Общее число голосов'),
        ),
    ]
