# Generated by Django 3.2.8 on 2021-11-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20211105_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uik',
            name='num_tik',
            field=models.ManyToManyField(to='mainapp.Tik'),
        ),
    ]
