# Generated by Django 3.2.8 on 2021-11-15 20:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20211111_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='birthday',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Дата рождения'),
        ),
    ]
