# Generated by Django 3.2.8 on 2021-11-05 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_uik_num_tik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tik',
            name='num_tik',
            field=models.CharField(max_length=200, verbose_name='Номер ТИК'),
        ),
        migrations.AlterField(
            model_name='uik',
            name='num_tik',
            field=models.ManyToManyField(to='mainapp.Tik', verbose_name='Номер ТИК'),
        ),
        migrations.AlterField(
            model_name='uik',
            name='num_uik',
            field=models.IntegerField(unique=True, verbose_name='Номер участка'),
        ),
    ]
