# Generated by Django 3.2.8 on 2021-10-28 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20211027_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocol1',
            name='num_uik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.uik', verbose_name='Номер участка'),
        ),
        migrations.AlterField(
            model_name='protocol2',
            name='num_uik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.uik', verbose_name='Номер участка'),
        ),
    ]
