# Generated by Django 3.2.8 on 2021-11-02 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_merge_0003_alter_uik_num_tik_0003_auto_20211025_1307'),
        ('mainapp', '0007_auto_20211028_1309'),
    ]

    operations = [
    ]
