# Generated by Django 3.2.8 on 2021-10-11 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=300, verbose_name='ФИО')),
                ('snils', models.CharField(max_length=11, unique=True, verbose_name='Номер СНИЛС')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
