# Generated by Django 3.2.8 on 2021-10-21 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_permit_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='id_user',
        ),
        migrations.RemoveField(
            model_name='role',
            name='role_user',
        ),
        migrations.DeleteModel(
            name='Permit',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
