# Generated by Django 3.2.8 on 2021-10-22 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_permit_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='snils',
            new_name='username',
        ),
    ]
