# Generated by Django 3.2.8 on 2021-10-25 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role_user',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='Permit',
        ),
    ]
