# Generated by Django 3.2.8 on 2021-10-25 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20211025_1344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='id_user',
            new_name='user',
        ),
    ]
