# Generated by Django 3.2.8 on 2021-10-26 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_id_user_role_user'),
        ('accounts', '0009_alter_role_user'),
    ]

    operations = [
    ]
